import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Heading } from "./component/Heading";
import { FooterContent } from "./Footer/FooterContent";
import { ThemeProvider } from "./dropDown/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center gap-20">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Heading />
          {children}
          <FooterContent />
        </ThemeProvider>
      </body>
    </html>
  );
}
